package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const (
	genTag      = "// generate:reset"
	genFilename = "reset.gen.go"
)

func main() {
	err := filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return processPackage(path)
		}
		return nil
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "Ошибка: %v\n", err)
		os.Exit(1)
	}
}

func processPackage(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil // Пропускаем директории, которые не являются пакетами Go
	}

	for pkgName, pkg := range pkgs {
		var output strings.Builder
		hasResettable := false

		output.WriteString(fmt.Sprintf("// Code generated by reset-gen. DO NOT EDIT.\npackage %s\n\n", pkgName))

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE || !hasResetTag(genDecl) {
					continue
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					hasResettable = true
					generateResetMethod(&output, typeSpec.Name.Name, structType)
				}
			}
		}

		if hasResettable {
			targetPath := filepath.Join(dir, genFilename)
			formatted, err := format.Source([]byte(output.String()))
			if err != nil {
				return fmt.Errorf("ошибка форматирования в %s: %w", dir, err)
			}
			if err := os.WriteFile(targetPath, formatted, 0644); err != nil {
				return fmt.Errorf("ошибка записи файла %s: %w", targetPath, err)
			}
			fmt.Printf("Сгенерирован: %s\n", targetPath)
		}
	}
	return nil
}

func hasResetTag(decl *ast.GenDecl) bool {
	if decl.Doc == nil {
		return false
	}
	for _, comment := range decl.Doc.List {
		if strings.Contains(comment.Text, genTag) {
			return true
		}
	}
	return false
}

func generateResetMethod(w *strings.Builder, structName string, st *ast.StructType) {
	w.WriteString(fmt.Sprintf("func (r *%s) Reset() {\n", structName))
	w.WriteString("\tif r == nil { return }\n\n")

	for _, field := range st.Fields.List {
		for _, name := range field.Names {
			writeResetLogic(w, name.Name, field.Type)
		}
	}
	w.WriteString("}\n\n")
}

func writeResetLogic(w *strings.Builder, fieldName string, expr ast.Expr) {
	switch t := expr.(type) {
	case *ast.Ident:
		w.WriteString(fmt.Sprintf("\tr.%s = %s\n", fieldName, getZeroValue(t.Name)))

	case *ast.ArrayType:
		if t.Len == nil {
			w.WriteString(fmt.Sprintf("\tr.%s = r.%s[:0]\n", fieldName, fieldName))
		}

	case *ast.MapType:
		w.WriteString(fmt.Sprintf("\tclear(r.%s)\n", fieldName))

	case *ast.StarExpr:
		w.WriteString(fmt.Sprintf("\tif rs.%s != nil {\n", fieldName))

		if ident, ok := t.X.(*ast.Ident); ok && isPrimitive(ident.Name) {
			w.WriteString(fmt.Sprintf("\t\t*rs.%s = %s\n", fieldName, getZeroValue(ident.Name)))
		} else {
			w.WriteString(fmt.Sprintf("\t\tvar resetter any = rs.%s\n", fieldName))
			w.WriteString("\t\tif r, ok := resetter.(interface{ Reset() }); ok {\n")
			w.WriteString("\t\t\tr.Reset()\n")
			w.WriteString("\t\t}\n")
		}
		w.WriteString("\t}\n")
	}
}

func isPrimitive(typeName string) bool {
	switch typeName {
	case "bool",
		"string",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return true
	}
	return false
}

func getZeroValue(typeName string) string {
	switch typeName {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte", "rune":
		return "0"
	case "float32", "float64":
		return "0.0"
	default:
		return "nil"
	}
}
