package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const (
	genTag      = "// generate:reset"
	genFilename = "reset.gen.go"
)

var resetTemplate = template.Must(template.New("reset").Funcs(template.FuncMap{
	"isSlice": func(expr ast.Expr) bool {
		_, ok := expr.(*ast.ArrayType)
		return ok
	},
	"isSliceWithoutLen": func(expr ast.Expr) bool {
		if at, ok := expr.(*ast.ArrayType); ok {
			return at.Len == nil // []T
		}
		return false
	},
	"isMap": func(expr ast.Expr) bool {
		_, ok := expr.(*ast.MapType)
		return ok
	},
	"isPointer": func(expr ast.Expr) bool {
		_, ok := expr.(*ast.StarExpr)
		return ok
	},
	"isPrimitive": func(name string) bool {
		switch name {
		case "bool", "string",
			"int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
			"byte", "rune",
			"float32", "float64",
			"complex64", "complex128":
			return true
		}
		return false
	},
	"zero": func(name string) string {
		switch name {
		case "string":
			return `""`
		case "bool":
			return "false"
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
			"byte", "rune",
			"float32", "float64",
			"complex64", "complex128":
			return "0"
		default:
			return "nil"
		}
	},
	"identName": func(expr ast.Expr) (string, bool) {
		id, ok := expr.(*ast.Ident)
		if ok {
			return id.Name, true
		}
		return "", false
	},
}).Parse(`
{{- define "resetMethod" -}}
func (r *{{.Name}}) Reset() {
    if r == nil {
        return
    }

{{- range .Fields}}
    {{- $field := . }}
    {{- $type := $field.Type }}

    {{- if isSliceWithoutLen $type }}
    r.{{$field.Name}} = r.{{$field.Name}}[:0]

    {{- else if isSlice $type }}
    // fixed-size array [N]T — zeroing not implemented (or use loop)
    // r.{{$field.Name}} = [len(r.{{$field.Name}})]{{with $t := identName $type.Elt}}{{$t}}{{end}}{}

    {{- else if isMap $type }}
    clear(r.{{$field.Name}})

    {{- else if isPointer $type }}
    if r.{{$field.Name}} != nil {
        {{- if $elemIdent, ok := identName $type.X; ok }}
            {{- if isPrimitive $elemIdent }}
        *r.{{$field.Name}} = {{zero $elemIdent}}
            {{- else }}
        // Pointer to non-primitive — call Reset() if available
        if res, ok := any(r.{{$field.Name}}).(interface{ Reset() }); ok {
            res.Reset()
        }
            {{- end }}
        {{- else }}
        // Complex pointer type — manual handling may be needed
        {{- end }}
    }

    {{- else if $id, ok := identName $type; ok }}
    r.{{$field.Name}} = {{zero $id}}

    {{- else }}
    // Unsupported field type: {{printf "%#v" $type}} — zeroing skipped

    {{- end -}}
{{- end }}
}
{{end -}}
`))

type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

type FieldInfo struct {
	Name string
	Type ast.Expr
}

func main() {
	err := filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return processPackage(path)
		}
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Ошибка: %v\n", err)
		os.Exit(1)
	}
}

func processPackage(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil // // Пропускаем директории, которые не являются пакетами Go
	}

	for pkgName, pkg := range pkgs {
		var structs []StructInfo

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				if !hasResetTag(genDecl) {
					continue
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					fields := make([]FieldInfo, 0, len(structType.Fields.List))
					for _, f := range structType.Fields.List {
						for _, name := range f.Names {
							fields = append(fields, FieldInfo{
								Name: name.Name,
								Type: f.Type,
							})
						}
					}

					structs = append(structs, StructInfo{
						Name:   typeSpec.Name.Name,
						Fields: fields,
					})
				}
			}
		}

		if len(structs) == 0 {
			continue
		}

		var buf bytes.Buffer
		header := fmt.Sprintf(`// Code generated by reset-gen. DO NOT EDIT.
package %s

`, pkgName)
		buf.WriteString(header)

		for _, st := range structs {
			if err := resetTemplate.ExecuteTemplate(&buf, "resetMethod", st); err != nil {
				return fmt.Errorf("error while executing template %s: %w", st.Name, err)
			}
			buf.WriteString("\n")
		}

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			return fmt.Errorf("formatting failed in %s: %w", dir, err)
		}

		target := filepath.Join(dir, genFilename)
		if err := os.WriteFile(target, formatted, 0644); err != nil {
			return fmt.Errorf("write %s failed: %w", target, err)
		}

		fmt.Printf("Generated: %s\n", target)
	}

	return nil
}

func hasResetTag(decl *ast.GenDecl) bool {
	if decl.Doc == nil {
		return false
	}
	for _, c := range decl.Doc.List {
		if strings.Contains(c.Text, genTag) {
			return true
		}
	}
	return false
}
